[package]
name = "lynes"
version = "0.1.0"
edition = "2024"

[features]
default = []
wgpu = ["dep:wgpu", "dep:winit", "dep:pollster"]
chafa = ["dep:chafa-syms-rs", "dep:crossterm"]

[dependencies]
colored = "3"
modular-bitfield = "0.13"
wgpu = { version = "30", optional = true }
winit = { version = "0.30", optional = true }
pollster = { version = "1", optional = true }
chafa-syms-rs = { version = "0.1.1", optional = true }
crossterm = { version = "0.29", optional = true }
