[package]
name = "lynes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
modular-bitfield = "0.11.2"
rand = "0.8.5"
sdl2 = "0.35.2"
